disabled_rules:
  - opening_brace

opt_in_rules:
  - force_unwrapping
  - implicit_return
  - closure_spacing
  - redundant_type_annotation
  - sorted_imports

identifier_name:
  min_length: 2
  excluded:
    - id

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 400
  error: 600

excluded:
  - .build
  - BedTermKit/.build
  - .worktrees
  - .xc-dev
  - BedTermTests/Mocks
