// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_IOS_H
#define BEDTERM_IOS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef double CGFloat;

typedef void (*BtIosBackCallback)(void *ctx);

typedef void (*BtIosOnSendCallback)(void *ctx, const uint8_t *bytes, uintptr_t len);

typedef void (*BtIosOnResizeCallback)(void *ctx, uint16_t cols, uint16_t rows);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Boot the Rust coordinator. If `request_local_network` is non-null and
 * onboarding has not been completed, the onboarding flow is created
 * internally. When onboarding finishes, the coordinator transitions to
 * the hosts root automatically.
 *
 * # Safety
 * Main thread. `window` is a +1 retained `UIWindow *`.
 */
void bt_ios_start_root_coordinator(void *window,
                                   void (*request_local_network)(void *ctx,
                                                                 void (*completion)(void*)));

/**
 * UI-test entry point: create a terminal VC inside a
 * `UINavigationController`, feed raw bytes, and install as the window's
 * root. Replaces the old 3-call pattern (`bt_ios_create_vc` +
 * `bt_ios_vc_metal_view` + `bt_ios_view_feed_bytes`).
 *
 * # Safety
 * Main thread. `window` is a +1 retained `UIWindow *`. `bytes` must be
 * valid for `len` bytes for the duration of the call.
 */
void bt_ios_install_terminal_fixture(void *window, const uint8_t *bytes, uintptr_t len);

/**
 * True iff the user has finished the onboarding flow. Defaults to
 * `false` on first launch.
 */
bool bt_ios_settings_onboarding_completed(void);

/**
 * Called by Swift at app launch and on `NSLocale.currentLocaleDidChange`
 * notifications. UTF-8 nul-terminated locale identifier (e.g. "zh-Hans",
 * "en", "ja"). NULL is treated as "reset to default" (uses "en" fallback).
 *
 * # Safety
 * `code` must be NULL or point to a valid nul-terminated UTF-8 string.
 */
void bt_ios_set_locale(const char *code);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_IOS_H */
