// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_IOS_H
#define BEDTERM_IOS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Vertical gap between adjacent blocks. Blocks now butt against each other;
 * the hairline divider above each header is the only thing separating one
 * block from the next.
 */
#define INTER_BLOCK_GAP_PT 0.0

/**
 * Horizontal inset between the panel's left edge and cell column 0.
 */
#define CELL_LEFT_INSET_PT 12.0

/**
 * Hairline thickness drawn in the gap between blocks.
 */
#define DIVIDER_THICKNESS_PT 1.0

/**
 * Horizontal inset for the divider hairline — slightly indented from the
 * screen edge so it reads as a list separator rather than a hard rule.
 */
#define DIVIDER_HORIZONTAL_INSET_PT 16.0

/**
 * Maximum number of newline characters stored in `stylized_command` or
 * `stylized_output`. Bytes beyond this limit are silently dropped so a
 * long-running command with voluminous output doesn't grow the in-memory
 * capture without bound.
 */
#define MAX_BLOCK_OUTPUT_LINES 5000

/**
 * Sentinel for a still-running block's `end_line`. Picked outside the legal
 * `i32` grid-line range alacritty produces. Public so the FFI layer can
 * surface it to Swift.
 */
#define BLOCK_END_LINE_RUNNING INT32_MIN

#define BT_BLOCK_END_LINE_RUNNING BLOCK_END_LINE_RUNNING

#define BT_CLI_AGENT_NONE 0

#define BT_CLI_AGENT_CLAUDE 1

#define BT_CLI_AGENT_GEMINI 2

#define BT_CLI_AGENT_CODEX 3

#define BT_CLI_AGENT_AMP 4

#define BT_CLI_AGENT_DROID 5

#define BT_CLI_AGENT_OPENCODE 6

#define BT_CLI_AGENT_COPILOT 7

#define BT_CLI_AGENT_PI 8

#define BT_CLI_AGENT_AUGGIE 9

#define BT_CLI_AGENT_CURSOR_CLI 10

#define BT_CLI_AGENT_GOOSE 11

#define BT_CLI_AGENT_HERMES 12

#define BT_CLI_AGENT_VIBE 13

/**
 * Two triangles per cell.
 */
#define VERTICES_PER_CELL 6

/**
 * Two triangles per panel.
 */
#define VERTICES_PER_PANEL 6

#define HORIZONTAL_PADDING_PT 12.0

#define BADGE_DIAMETER_PT 28.0

#define ICON_SIZE_PT 14.0

#define BADGE_TEXT_GAP_PT 8.0

#define ROW_GAP_PT 2.0

#define FOREGROUND 0

#define BACKGROUND 1

#define BLACK 2

#define RED 3

#define GREEN 4

#define YELLOW 5

#define BLUE 6

#define MAGENTA 7

#define CYAN 8

#define WHITE 9

#define BRIGHT_BLACK 10

#define BRIGHT_RED 11

#define BRIGHT_GREEN 12

#define BRIGHT_YELLOW 13

#define BRIGHT_BLUE 14

#define BRIGHT_MAGENTA 15

#define BRIGHT_CYAN 16

#define BRIGHT_WHITE 17

#define BT_MODE_ALT_SCREEN (1 << 0)

#define BT_MODE_BRACKETED_PASTE (1 << 1)

#define BT_MODE_MOUSE_REPORT (1 << 2)

#define BT_MODE_APP_CURSOR (1 << 3)

#define BT_MODE_APP_KEYPAD (1 << 4)

#define BT_MODE_FOCUS_IN_OUT (1 << 5)

/**
 * Result code matching the C header's `BtSSHResultCode` enum.
 */
typedef enum BtSSHResultCode {
  BtSSHResultOk = 0,
  BtSSHResultDnsResolution = 1,
  BtSSHResultTcpRefused = 2,
  BtSSHResultTimeout = 3,
  BtSSHResultHandshakeFailed = 4,
  BtSSHResultAuthenticationFailed = 5,
  BtSSHResultHostKeyMismatch = 8,
  BtSSHResultDisconnected = 9,
  BtSSHResultPeerReset = 10,
  BtSSHResultShellExited = 11,
  BtSSHResultOther = 99,
} BtSSHResultCode;

/**
 * Session lifecycle state. Transitions are always monotone:
 * Idle → Connecting → Open → Closed.
 */
typedef enum BtSessionState {
  Idle = 0,
  Connecting = 1,
  Open = 2,
  Closed = 3,
} BtSessionState;

typedef struct BtTerm BtTerm;

/**
 * Opaque handle owning a running SSH terminal session.
 *
 * Created by [`bt_terminal_session_create`], freed by
 * [`bt_terminal_session_close`].
 */
typedef struct BtTerminalSessionHandle BtTerminalSessionHandle;

typedef void (*SaveResultFn)(void*, const char*);

typedef void (*ConnectFn)(void*, const char*);

typedef void (*DisconnectFn)(void*);

typedef void (*AlertFn)(void*, const char*, const char*, const char*, const char*);

typedef void (*MismatchCallback)(void*);

/**
 * Generic completion: `code` + optional detail `msg`.
 */
typedef void (*BtSSHCompletion)(void *ctx, enum BtSSHResultCode code, const void *msg, int32_t extra);

/**
 * Output-data sink. Called per inbound chunk on the main queue.
 */
typedef void (*BtSSHOutputSink)(void *ctx, const uint8_t *bytes, uintptr_t len);

typedef struct BtBlockView {
  uint64_t id;
  int32_t start_line;
  /**
   * `BT_BLOCK_END_LINE_RUNNING` while the block is running.
   */
  int32_t end_line;
  /**
   * 1 if running, 0 otherwise.
   */
  uint8_t is_running;
  uint8_t has_exit_code;
  uint8_t _pad[2];
  int32_t exit_code;
  /**
   * 0 when the shell didn't ship `dur=`.
   */
  uint64_t duration_ms;
  uint8_t has_duration;
  uint8_t _pad2[7];
  /**
   * UTF-8 bytes for command. `null` + len=0 when empty.
   */
  const uint8_t *command;
  uintptr_t command_len;
  /**
   * UTF-8 bytes for working directory. `null` + len=0 when missing.
   */
  const uint8_t *cwd;
  uintptr_t cwd_len;
  /**
   * UTF-8 bytes for git branch (short name or short SHA when
   * detached). `null` + len=0 when cwd is outside a repo or the
   * shell-integration didn't ship the field.
   */
  const uint8_t *git_branch;
  uintptr_t git_branch_len;
  /**
   * 1 if `frozen_snapshot` is available (sealed block), 0 otherwise.
   */
  uint8_t has_frozen_snapshot;
  /**
   * CLI agent tag — `0` = none / unrecognised, otherwise one of the
   * `BT_CLI_AGENT_*` constants below. Stable across releases; new
   * agents append. Identifying a known agent lets the host paint a
   * brand icon next to the block header; does NOT change layout.
   */
  uint8_t cli_agent;
  uint8_t _pad3[2];
  /**
   * Live body height in grid rows. For sealed blocks this equals
   * `end_line - start_line`. For running blocks this is the block
   * grid's current `used_rows()` — the bottom-most non-blank visible
   * row + 1 (plus any history). The host should use this for the
   * block's body extent so a streaming TUI grows the block in real
   * time without pre-allocating the full PTY screen height.
   */
  uint32_t body_rows;
} BtBlockView;

typedef double CGFloat;

/**
 * Opaque callback type fired when the in-VC back button is tapped.
 *
 * Defined unconditionally (no `#[cfg(target_os = "ios")]`) so cbindgen
 * emits the typedef in the generated C header — Swift tests reference
 * it by name (e.g. `IosTerminalFFITests.onSendCallback: BtIosOnSendCallback`).
 * The FFI entry points themselves inline the bare-fn signature so
 * cbindgen also gets a plain nullable C function-pointer parameter
 * (it doesn't unwrap `Option<TypeAlias>`).
 */
typedef void (*BtIosBackCallback)(void *ctx);

/**
 * PTY-byte sink callback installed on `BtIosMetalInputView`. Swift
 * tests reference this typedef by name; see `BtIosBackCallback` for
 * the cbindgen-visibility rationale.
 */
typedef void (*BtIosOnSendCallback)(void *ctx, const uint8_t *bytes, uintptr_t len);

/**
 * Grid-resize callback fired from `BtIosMetalInputView::layoutSubviews`.
 * Swift tests reference this typedef by name; see `BtIosBackCallback`
 * for the cbindgen-visibility rationale.
 */
typedef void (*BtIosOnResizeCallback)(void *ctx, uint16_t cols, uint16_t rows);

/**
 * Corner radius applied to the card layer.
 * Mirrors `RoundedRectangle(cornerRadius: 10)` in `ShadcnCard`.
 */
#define FormSectionMetrics_CARD_CORNER_RADIUS 10.0

/**
 * CALayer border width — `.stroke(..., lineWidth: 1)`.
 */
#define FormSectionMetrics_CARD_BORDER_WIDTH 1.0

/**
 * Padding inside the card on all four edges — `.padding(16)`.
 */
#define FormSectionMetrics_CARD_PADDING 16.0

/**
 * Spacing between the title and the description inside the card
 * header — `VStack(alignment: .leading, spacing: 4)`.
 */
#define FormSectionMetrics_HEADER_TITLE_DESCRIPTION_SPACING 4.0

/**
 * Spacing between the header block and the first field row —
 * outer `VStack(alignment: .leading, spacing: 16)`.
 */
#define FormSectionMetrics_HEADER_TO_ROWS_SPACING 16.0

/**
 * Vertical spacing between rows inside the card —
 * `VStack(spacing: 14)` in `ShadcnCard`.
 */
#define FormSectionMetrics_ROW_SPACING 14.0

/**
 * Legacy inset-grouped section corner radius (kept for the old
 * `form_section` API used by the Settings VC).
 */
#define FormSectionMetrics_LEGACY_CORNER_RADIUS 8.0

/**
 * Legacy inset-grouped section border width.
 */
#define FormSectionMetrics_LEGACY_BORDER_WIDTH 0.5

/**
 * Gap between the uppercase section header and the card below it.
 */
#define FormSectionMetrics_EXTERNAL_HEADER_TO_CARD_SPACING 8.0

/**
 * Gap between the card and the description sentence below it.
 */
#define FormSectionMetrics_CARD_TO_EXTERNAL_DESCRIPTION_SPACING 8.0

/**
 * Horizontal indent (in points) of the external section header /
 * description relative to the card edge. Matches the card's internal
 * horizontal padding so headers align with the leading edge of in-card
 * text.
 */
#define FormSectionMetrics_EXTERNAL_HEADER_INSET 16.0

/**
 * Corner radius applied to the row's CALayer.
 */
#define ListRowMetrics_CORNER_RADIUS 10.0

/**
 * CALayer border width.
 */
#define ListRowMetrics_BORDER_WIDTH 1.0

/**
 * Horizontal padding inside the row (leading + trailing).
 */
#define ListRowMetrics_HORIZONTAL_PADDING 16.0

/**
 * Vertical padding inside the row (top + bottom).
 */
#define ListRowMetrics_VERTICAL_PADDING 12.0

/**
 * Vertical spacing between the title and subtitle labels.
 */
#define ListRowMetrics_TITLE_SUBTITLE_SPACING 2.0

/**
 * Horizontal spacing between the text stack and trailing accessory.
 */
#define ListRowMetrics_TEXT_TO_ACCESSORY_SPACING 12.0

/**
 * SF symbol point size for the trailing chevron.
 */
#define ListRowMetrics_CHEVRON_POINT_SIZE 13.0

/**
 * Side length of the bordered square wrapping the auth badge.
 * Mirrors SwiftUI `HostRow.authBadge`'s `.frame(width: 24, height: 24)`.
 */
#define ListRowMetrics_BADGE_SIZE 24.0

/**
 * Corner radius of the badge square — matches `RoundedRectangle(cornerRadius: 6)`.
 */
#define ListRowMetrics_BADGE_CORNER_RADIUS 6.0

/**
 * SF symbol point size for the badge glyph — `.caption2.weight(.semibold)`
 * is ~11pt in SwiftUI.
 */
#define ListRowMetrics_BADGE_GLYPH_POINT_SIZE 11.0

/**
 * Outer corner radius (the rounded "pill" enclosing both tabs).
 */
#define SegmentedControlMetrics_OUTER_CORNER_RADIUS 8.0

/**
 * Intrinsic height of the control (matches `ShadcnSegmented`).
 */
#define SegmentedControlMetrics_HEIGHT 34.0

/**
 * Inset between the outer border and the selected tab background.
 */
#define SegmentedControlMetrics_SELECTION_INSET 3.0

#define XS 4.0

#define SM 8.0

#define MD 12.0

#define LG 16.0

#define XL 24.0

/**
 * Intrinsic field height; matches the SwiftUI `ShadcnTextField` value.
 */
#define TextFieldMetrics_FIELD_HEIGHT 36.0

/**
 * Vertical spacing between the field's label and the input box.
 */
#define TextFieldMetrics_LABEL_TO_FIELD_SPACING 6.0

#define WEIGHT_REGULAR 0.0

#define WEIGHT_MEDIUM 0.23

#define WEIGHT_SEMIBOLD 0.3

#define WEIGHT_BOLD 0.4

/**
 * Default header band height in points. Mirrors Swift's
 * `BlockListContainerViewController.headerHeightPt`.
 */
#define HEADER_HEIGHT_PT 56.0

/**
 * Tolerance (in points) for snapping back to `.followsBottom` once the
 * user scrolls within this distance of the bottom edge.
 */
#define PIN_TOLERANCE_PT 24.0

/**
 * Outer dpad container dimension (square). Exported so the VC can size /
 * position it in `viewDidLayoutSubviews`.
 */
#define DPAD_SIZE 80.0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern double CACurrentMediaTime(void);

/**
 * Called by Swift at app launch and on `NSLocale.currentLocaleDidChange`
 * notifications. UTF-8 nul-terminated locale identifier (e.g. "zh-Hans",
 * "en", "ja"). NULL is treated as "reset to default" (uses "en" fallback).
 *
 * # Safety
 * `code` must be NULL or point to a valid nul-terminated UTF-8 string.
 */
void bt_ios_set_locale(const char *code);

/**
 * Return a pointer to the embedded `bedterm-integration.sh` payload
 * and write its length through `out_len`.
 *
 * The returned pointer is **static** — it lives in the staticlib's
 * `.rodata` for the lifetime of the process. Callers must not free it
 * and must not mutate the bytes. The payload is not nul-terminated;
 * always use the returned length.
 *
 * # Safety
 * `out_len` must be a valid, writable pointer to a `usize`. Pass NULL
 * to skip the length write (only useful as a liveness check).
 */
const uint8_t *bt_ios_shell_integration_payload(uintptr_t *out_len);

/**
 * Called from Swift's AppDelegate to boot the Rust coordinator.
 * `window` is a +1 retained `UIWindow *`.
 */
void bt_ios_start_root_coordinator(void *window);

/**
 * Called from Swift when the onboarding flow completes. Transitions to
 * the hosts root (same as `installHostsRoot` in the Swift version).
 */
void add_trampoline(void *ctx);

/**
 * Create a connect-form VC.
 *
 * - `editing_id_or_null`: UTF-8, nul-terminated UUID string of an
 *   existing host to edit, or NULL for "Add Host".
 * - `connect_on_save`: when true, the Save bar button reads
 *   "Save & Connect" — mirrors the SwiftUI
 *   `ConnectionFormScreen.primaryActionTitle` branch.
 * - `on_done`: fires on the main thread with the saved entry's UUID
 *   string once the user successfully saves. The string is borrowed
 *   for the duration of the call.
 * - `on_cancel`: fires when the user taps Cancel.
 * - `ctx`: opaque pointer threaded into both callbacks.
 *
 * Returns +1 retained; release via [`bt_ios_release_connect_form_vc`].
 *
 * # Safety
 * Callbacks invoke on the main thread. `ctx` is never dereffed by Rust.
 */
void *bt_ios_create_connect_form_vc(const char *editing_id_or_null,
                                    bool connect_on_save,
                                    void (*on_done)(void *ctx,
                                                    const char *id_string,
                                                    bool connect_now),
                                    void (*on_cancel)(void *ctx),
                                    void *ctx);

/**
 * Release a connect-form `UIViewController *` previously returned by
 * [`bt_ios_create_connect_form_vc`]. Safe to call with NULL.
 *
 * # Safety
 * `vc_ptr` must have been returned by `bt_ios_create_connect_form_vc`
 * and not yet released.
 */
void bt_ios_release_connect_form_vc(void *vc_ptr);

/**
 * Install the save-result side-effect callback.
 */
void bt_ios_connect_form_vm_set_callbacks(SaveResultFn save_result_cb,
                                          void *save_result_ctx,
                                          void (*_alert_cb)(void*, const char*),
                                          void *_alert_ctx);

void *bt_ios_create_hosts_list_vc(void (*on_add)(void *ctx), void *ctx);

void bt_ios_release_hosts_list_vc(void *vc_ptr);

bool bt_ios_hosts_save_blob(const char *uuid, const uint8_t *bytes, uintptr_t len);

void bt_ios_hosts_vm_load_from_store(void);

void bt_ios_hosts_vm_set_callbacks(ConnectFn connect_cb,
                                   void *connect_ctx,
                                   DisconnectFn disconnect_cb,
                                   void *disconnect_ctx,
                                   AlertFn alert_cb,
                                   void *alert_ctx);

int32_t bt_ios_hosts_vm_request_connect(const char *uuid, char **out_uuid);

void bt_ios_hosts_vm_connect_completed_session(const char *uuid);

void bt_ios_hosts_vm_connect_completed_error(const char *uuid);

/**
 * Create the full onboarding-flow VC — a `UINavigationController`
 * subclass (`BtIosOnboardingFlowVC`) that owns the `OnboardingState`
 * state machine and pushes each step VC as the user advances.
 *
 * The returned pointer is +1 retained; release with `bt_ios_release_vc`.
 *
 * - `on_completed`: fired once when onboarding finishes.
 * - `ctx`: opaque host context threaded into `on_completed`.
 * - `request_local_network`: injected by Swift to trigger the Bonjour-based
 *   Local Network permission prompt. When NULL the permission step is
 *   skipped (harmless: the OS prompts on first actual LAN connection).
 *   Called with `(ctx, completion)` — Swift runs the probe and calls
 *   `completion(ctx)` on the main thread when the OS resolves the prompt.
 *
 * # Safety
 * All callbacks are stored and invoked on the main thread only.
 */
void *bt_ios_create_onboarding_flow_vc(void (*on_completed)(void *ctx),
                                       void *ctx,
                                       void (*request_local_network)(void *ctx,
                                                                     void (*completion)(void*)));

/**
 * Create the Rust-built Settings `UIViewController *` (returned as
 * `*mut c_void`). +1 retained — release via `bt_ios_release_settings_vc`.
 *
 * - `on_done`: callback fired on the main thread when the user taps
 *   the navigation-bar Done button (may be NULL).
 * - `ctx`: opaque pointer threaded through to `on_done` (may be NULL).
 *
 * # Safety
 * `on_done` is invoked on the main thread. `ctx` is never dereffed by
 * Rust; the Swift host owns its lifetime until either it clears the
 * pair or the VC is released.
 */
void *bt_ios_create_settings_vc(void (*on_done)(void *ctx), void *ctx);

/**
 * Release a Settings `UIViewController *` previously returned by
 * `bt_ios_create_settings_vc`. Safe to call with NULL.
 *
 * # Safety
 * `vc_ptr` must have been returned by `bt_ios_create_settings_vc` and
 * not yet released.
 */
void bt_ios_release_settings_vc(void *vc_ptr);

/**
 * True iff the user has finished the onboarding flow. Defaults to
 * `false` on first launch.
 */
bool bt_ios_settings_onboarding_completed(void);

/**
 * Create a `BtIosToasterView *` (returned as `*mut c_void`). The result
 * is **+1 retained** and owned by the caller; release with
 * `Retained::from_raw`.
 *
 * # Safety
 * Must be called on the main thread (UIKit construction).
 */
void *bt_ios_toaster_view_new(void);

/**
 * Create the iOS terminal `UIViewController *` (returned as `*mut c_void` so
 * the C header can stay type-agnostic).
 *
 * - `on_back`: C callback fired when the back button is tapped (may be null).
 * - `ctx`: context pointer passed through to `on_back` (may be null).
 *
 * The returned pointer is a **+1 retained** `UIViewController` that the
 * caller owns. Release via `bt_ios_release_vc`.
 *
 * # Safety
 * `on_back` and `ctx` are stored and invoked on the main thread only.
 */
void *bt_ios_create_vc(void (*on_back)(void *ctx), void *ctx);

/**
 * Release a `UIViewController *` previously returned by `bt_ios_create_vc`.
 * Safe to call with null.
 *
 * # Safety
 * `vc_ptr` must be a pointer returned by `bt_ios_create_vc` and not yet
 * released.
 */
void bt_ios_release_vc(void *vc_ptr);

void *bt_ios_create_mismatch_vc(MismatchCallback on_trust, MismatchCallback on_reject, void *ctx);

void bt_ios_release_mismatch_vc(void *vc_ptr);

/**
 * Resolve the `BtIosMetalInputView *` embedded inside a VC returned by
 * `bt_ios_create_vc`. Returns NULL when the view didn't construct
 * (headless tests).
 *
 * # Safety
 * Main thread. `vc_ptr` must be a live VC pointer.
 */
void *bt_ios_vc_metal_view(void *vc_ptr);

/**
 * Feed raw terminal bytes into the `BtIosMetalInputView`'s owned grid.
 * `view_ptr` must be a +1 retained `BtIosMetalInputView *` (e.g. obtained
 * from the host VC). The call is a no-op when any argument is null / empty.
 *
 * # Safety
 * Must be called on the main thread. `view_ptr` must point to a live
 * `BtIosMetalInputView`. `bytes` must be valid for `len` bytes for the
 * duration of the call.
 */
void bt_ios_view_feed_bytes(void *view_ptr, const uint8_t *bytes, uintptr_t len);

/**
 * Create a new terminal session handle.
 *
 * Spawns a single-threaded tokio runtime and returns an opaque handle
 * ready for [`bt_terminal_session_connect`].
 *
 * Returns NULL if the tokio runtime could not be created.
 *
 * # Parameters
 *
 * - `state_cb`: nullable state-change callback. Fired on each lifecycle
 *   transition (Connecting → Open → Closed).
 * - `state_ctx`: opaque context threaded verbatim to `state_cb`.
 *
 * # Safety
 *
 * `state_cb` (if non-null) must be a valid function pointer valid for the
 * lifetime of the handle. `state_ctx` must remain valid for the same
 * duration.
 */
struct BtTerminalSessionHandle *bt_terminal_session_create(void (*state_cb)(void *ctx,
                                                                            enum BtSessionState state,
                                                                            enum BtSSHResultCode error_code,
                                                                            int32_t exit_code),
                                                           void *state_ctx);

/**
 * Connect to an SSH server, open a PTY shell, and optionally send a
 * bootstrap payload — all in one blocking call on the calling thread.
 *
 * On success: stores the client, transitions state → Open, fires
 * `state_cb`, starts the background read loop (if a data sink is
 * installed), then calls `completion(Ok)`.
 *
 * On error: transitions state → Closed with the appropriate error code,
 * then calls `completion(Err)`.
 *
 * # Parameters
 *
 * - `handle`: opaque handle from [`bt_terminal_session_create`].
 * - `host`: UTF-8 C string, remote hostname or IP. Must not be NULL.
 * - `port`: TCP port (typically 22).
 * - `username`: UTF-8 C string, SSH username. Must not be NULL.
 * - `credential_json`: UTF-8 C string JSON describing the credential.
 *   Must not be NULL.
 * - `bootstrap_payload`: nullable UTF-8 C string sent to the shell
 *   immediately after opening (e.g. a shell integration script).
 * - `cols` / `rows`: initial PTY dimensions in character cells.
 * - `timeout_ms`: if > 0, the entire connect + open_shell sequence is
 *   wrapped in a timeout. 0 means no timeout.
 * - `completion`: callback invoked with the connection result.
 * - `completion_ctx`: opaque context for `completion`.
 *
 * # Safety
 *
 * See the module-level safety documentation.
 */
void bt_terminal_session_connect(struct BtTerminalSessionHandle *handle,
                                 const char *host,
                                 uint16_t port,
                                 const char *username,
                                 const char *credential_json,
                                 const char *bootstrap_payload,
                                 uint16_t cols,
                                 uint16_t rows,
                                 uint64_t timeout_ms,
                                 BtSSHCompletion completion,
                                 void *completion_ctx);

/**
 * Install (or replace) the data sink for inbound PTY bytes.
 *
 * If the shell is already open and no read thread is running, calling
 * this function automatically spawns the background read loop.
 *
 * # Parameters
 *
 * - `handle`: opaque handle.
 * - `sink`: callback function pointer. Must be non-null.
 * - `sink_ctx`: opaque context threaded verbatim to `sink`.
 *
 * # Safety
 *
 * `sink` must be a valid function pointer valid for the lifetime of the
 * handle or until [`bt_terminal_session_close`] is called. `sink_ctx`
 * must remain valid for the same duration.
 */
void bt_terminal_session_set_data_sink(struct BtTerminalSessionHandle *handle,
                                       BtSSHOutputSink sink,
                                       void *sink_ctx);

/**
 * Replaces the per-session data sink with a direct feed into the given
 * `BtIosMetalInputView`. After this call, inbound PTY bytes are pushed
 * straight into the metal view's `BtTerm` renderer — no Swift pump task,
 * no `AsyncStream`, no C-callback trampoline through Swift.
 *
 * This is the Phase 3 bridge: the Swift `RustTerminalSession` pump task
 * (`startPumpTask`) and the `IosTerminalHost` feed-forwarding task can
 * both be retired once every session calls this function.
 *
 * # Safety
 *
 * `handle` must be a valid non-null pointer returned by
 * [`bt_terminal_session_create`]. `metal_view_ptr` must point to a live
 * `BtIosMetalInputView` that outlives the session. Must be called on the
 * main thread (the metal view is a UIKit object).
 */
void bt_terminal_session_attach_metal_view(struct BtTerminalSessionHandle *handle,
                                           void *metal_view_ptr);

/**
 * Fully tear down the session handle and free all resources.
 *
 * Signals the background read loop to stop, joins the read-loop thread,
 * takes and closes the SSH client, then deallocates the handle.
 *
 * After this call the handle pointer is invalid and must not be used
 * again. Safe to call with NULL.
 *
 * # Safety
 *
 * `handle` must be non-NULL and returned by [`bt_terminal_session_create`]
 * that has not already been passed to `bt_terminal_session_close`.
 */
void bt_terminal_session_close(struct BtTerminalSessionHandle *handle);

/**
 * # Safety
 * `h` must be a valid `BtTerm *` returned by `bt_term_new`.
 */
uintptr_t bt_term_block_count(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid `BtTerm *`; `out` must point to a writable
 * `BtBlockView`. String pointers in `*out` are invalidated by the next
 * call as described in the module-level docs.
 */
int bt_term_block_at(struct BtTerm *h, uintptr_t idx, struct BtBlockView *out);

/**
 * Return the human-readable display name for a CLI agent identified by
 * its `BT_CLI_AGENT_*` tag. Returns a static C string, or NULL when the
 * tag is `BT_CLI_AGENT_NONE` (0) or unknown (forward-compat).
 *
 * The returned pointer lives in the binary's `.rodata` and must NOT be
 * freed by the caller.
 */
const char *bt_cli_agent_display_name(uint8_t tag);

/**
 * Return the asset-catalog icon name for a CLI agent identified by its
 * `BT_CLI_AGENT_*` tag. Returns a static C string, or NULL when the agent
 * has no dedicated icon (caller should fall back to a generic glyph),
 * the tag is `BT_CLI_AGENT_NONE` (0), or unknown.
 *
 * The returned pointer lives in the binary's `.rodata` and must NOT be
 * freed by the caller.
 */
const char *bt_cli_agent_icon_name(uint8_t tag);

struct BtTerm *bt_term_new(uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_term_new` that has not yet been freed.
 */
void bt_term_free(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `bytes` must point to at least `len` bytes.
 */
void bt_term_feed(struct BtTerm *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_resize(struct BtTerm *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_by(struct BtTerm *h, int32_t delta);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_to_bottom(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scroll_offset(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scrollback_lines(const struct BtTerm *h);

/**
 * Return the terminal's current mode flags, packed as `BT_MODE_*` bits
 * defined in `term.rs`. Swift mirrors the layout in `BedTermMode`.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_mode(const struct BtTerm *h);

/**
 * Cursor's current grid line on the active screen. Swift records this on
 * each block boundary so Block view can later snapshot a row range that
 * covers the block.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_current_line(const struct BtTerm *h);

/**
 * Grid-absolute line index of the screen's bottom row. Block view uses
 * this as the body's upper bound for running blocks so that TUI cells
 * drawn *below* the cursor via cursor-positioning escapes (claude / fzf
 * / gum) stay visible.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_screen_bottom_line(const struct BtTerm *h);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_IOS_H */
