// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_CORE_H
#define BEDTERM_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Two triangles per cell.
 */
#define VERTICES_PER_CELL 6

#define VINTR 3

#define VEOF 4

#define VERASE 127

typedef struct BtMockTty BtMockTty;

typedef struct BtRenderer BtRenderer;

typedef struct BtTerm BtTerm;

typedef struct Flags Flags;

typedef struct CellSnapshot {
  /**
   * Unicode scalar of the cell. 0 = blank. Wide-char trailing halves use char 0 with WIDE_TRAILING flag.
   */
  uint32_t ch;
  /**
   * Foreground colour, RGBA packed big-endian-style: 0xRRGGBBAA.
   */
  uint32_t fg_rgba;
  /**
   * Background colour, same encoding.
   */
  uint32_t bg_rgba;
  /**
   * Bitfield: 1=bold, 2=underline, 4=inverse, 8=italic, 16=wide_leading, 32=wide_trailing.
   */
  uint16_t flags;
} CellSnapshot;

typedef struct BtSnapshotView {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  uint16_t cursor_row;
  const struct CellSnapshot *cells;
  uintptr_t cell_count;
} BtSnapshotView;





#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct BtTerm *bt_term_new(uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_term_new` that has not yet been freed.
 */
void bt_term_free(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `bytes` must point to at least `len` bytes.
 */
void bt_term_feed(struct BtTerm *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_resize(struct BtTerm *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be a valid pointer to a `BtSnapshotView`.
 * The cell pointer in `*out` is valid until the next mutating call or `bt_term_snapshot_release`.
 */
int bt_term_snapshot(struct BtTerm *h, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_snapshot_release(struct BtTerm *h);

/**
 * # Safety
 * `mtl_device` and `mtl_queue` must be non-null `id<MTLDevice>` /
 * `id<MTLCommandQueue>` pointers. They are borrowed for the renderer's
 * lifetime; the caller (Swift) retains them.
 */
struct BtRenderer *bt_renderer_new(const void *mtl_device, const void *mtl_queue);

/**
 * # Safety
 * `r` must be a pointer returned by `bt_renderer_new` not yet freed.
 */
void bt_renderer_free(struct BtRenderer *r);

/**
 * # Safety
 * `r` must be a live `BtRenderer` pointer.
 */
void bt_renderer_set_font(struct BtRenderer *r, float pixel_size, float device_pixel_ratio);

/**
 * Write the renderer's current cell size (in PIXELS, scaled by the dpr
 * passed to `bt_renderer_set_font`) into `*out_w` and `*out_h`. Swift
 * divides by its display scale to obtain the point-space cell size used
 * for laying out CALayer overlays (cursor, selection) — keeping them
 * pixel-aligned with the glyphs the renderer paints.
 *
 * # Safety
 * `r` must be a live `BtRenderer`. `out_w` and `out_h` must be valid
 * pointers to `u32` slots the caller owns.
 */
void bt_renderer_cell_pixel_size(const struct BtRenderer *r, uint32_t *out_w, uint32_t *out_h);

/**
 * # Safety
 * `r` must be a live `BtRenderer`. `term` must be a live `BtTerm` or null
 * (null is treated as "no terminal yet"). `drawable_texture` must be a
 * live `id<MTLTexture>`.
 */
int bt_renderer_draw(struct BtRenderer *r,
                     const struct BtTerm *term,
                     const void *drawable_texture,
                     uint32_t viewport_width_px,
                     uint32_t viewport_height_px,
                     double time_seconds);

/**
 * # Safety
 * `opts_json` must be either null or point to a NUL-terminated UTF-8 string
 * owned by the caller for the duration of this call.
 */
struct BtMockTty *bt_mock_tty_create(uint32_t program, const char *opts_json);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_mock_tty_create` that has not been freed.
 */
void bt_mock_tty_free(struct BtMockTty *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_mock_tty_set_output_callback(struct BtMockTty *h, void (*cb)(const uint8_t*,
                                                                     uintptr_t,
                                                                     void*), void *user_data);

/**
 * # Safety
 * `h` must be valid; `bytes` must point to at least `len` bytes (or be null when len == 0).
 */
int32_t bt_mock_tty_write(struct BtMockTty *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be valid.
 */
void bt_mock_tty_resize(struct BtMockTty *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be valid.
 */
void bt_mock_tty_tick(struct BtMockTty *h, uint64_t now_ms);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_CORE_H */
