// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_CORE_H
#define BEDTERM_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct BtTerm BtTerm;

typedef struct CellSnapshot {
  /**
   * Unicode scalar of the cell. 0 = blank. Wide-char trailing halves use char 0 with WIDE_TRAILING flag.
   */
  uint32_t ch;
  /**
   * Foreground colour, RGBA packed big-endian-style: 0xRRGGBBAA.
   */
  uint32_t fg_rgba;
  /**
   * Background colour, same encoding.
   */
  uint32_t bg_rgba;
  /**
   * Bitfield: 1=bold, 2=underline, 4=inverse, 8=italic, 16=wide_leading, 32=wide_trailing.
   */
  uint16_t flags;
} CellSnapshot;

typedef struct BtSnapshotView {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  uint16_t cursor_row;
  const struct CellSnapshot *cells;
  uintptr_t cell_count;
} BtSnapshotView;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct BtTerm *bt_term_new(uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_term_new` that has not yet been freed.
 */
void bt_term_free(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `bytes` must point to at least `len` bytes.
 */
void bt_term_feed(struct BtTerm *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_resize(struct BtTerm *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be a valid pointer to a `BtSnapshotView`.
 * The cell pointer in `*out` is valid until the next mutating call or `bt_term_snapshot_release`.
 */
int bt_term_snapshot(struct BtTerm *h, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_snapshot_release(struct BtTerm *h);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_CORE_H */
