// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_CORE_H
#define BEDTERM_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of newline characters stored in `stylized_command` or
 * `stylized_output`. Bytes beyond this limit are silently dropped so a
 * long-running command with voluminous output doesn't grow the in-memory
 * capture without bound.
 */
#define MAX_BLOCK_OUTPUT_LINES 5000

/**
 * Sentinel for a still-running block's `end_line`. Picked outside the legal
 * `i32` grid-line range alacritty produces. Public so the FFI layer can
 * surface it to Swift.
 */
#define BLOCK_END_LINE_RUNNING INT32_MIN

#define BT_BLOCK_END_LINE_RUNNING BLOCK_END_LINE_RUNNING

#define BT_CLI_AGENT_NONE 0

#define BT_CLI_AGENT_CLAUDE 1

#define BT_CLI_AGENT_GEMINI 2

#define BT_CLI_AGENT_CODEX 3

#define BT_CLI_AGENT_AMP 4

#define BT_CLI_AGENT_DROID 5

#define BT_CLI_AGENT_OPENCODE 6

#define BT_CLI_AGENT_COPILOT 7

#define BT_CLI_AGENT_PI 8

#define BT_CLI_AGENT_AUGGIE 9

#define BT_CLI_AGENT_CURSOR_CLI 10

#define BT_CLI_AGENT_GOOSE 11

#define BT_CLI_AGENT_HERMES 12

#define BT_CLI_AGENT_VIBE 13

#define MAX_BLOCKS_PER_SNAPSHOT 100

#define CURRENT_VERSION 1

#define MAX_SNAPSHOTS_PER_HOST 10

/**
 * Two triangles per cell.
 */
#define VERTICES_PER_CELL 6

/**
 * Two triangles per panel.
 */
#define VERTICES_PER_PANEL 6

#define BT_MODE_ALT_SCREEN (1 << 0)

#define BT_MODE_BRACKETED_PASTE (1 << 1)

#define BT_MODE_MOUSE_REPORT (1 << 2)

#define BT_MODE_APP_CURSOR (1 << 3)

#define BT_MODE_APP_KEYPAD (1 << 4)

#define BT_MODE_FOCUS_IN_OUT (1 << 5)

typedef struct BtRenderer BtRenderer;

typedef struct BtTerm BtTerm;

/**
 * Backing storage that keeps the `CString` allocations alive for as long as
 * the `CSnapshotList` is live.
 */
typedef struct OwnedListBacking OwnedListBacking;

/**
 * Opaque handle. Allocated by `init`, freed by `close`.
 */
typedef struct PersistenceHandle PersistenceHandle;

typedef struct Terminal Terminal;

typedef struct BtBlockView {
  uint64_t id;
  int32_t start_line;
  /**
   * `BT_BLOCK_END_LINE_RUNNING` while the block is running.
   */
  int32_t end_line;
  /**
   * 1 if running, 0 otherwise.
   */
  uint8_t is_running;
  uint8_t has_exit_code;
  uint8_t _pad[2];
  int32_t exit_code;
  /**
   * 0 when the shell didn't ship `dur=`.
   */
  uint64_t duration_ms;
  uint8_t has_duration;
  uint8_t _pad2[7];
  /**
   * UTF-8 bytes for command. `null` + len=0 when empty.
   */
  const uint8_t *command;
  uintptr_t command_len;
  /**
   * UTF-8 bytes for working directory. `null` + len=0 when missing.
   */
  const uint8_t *cwd;
  uintptr_t cwd_len;
  /**
   * UTF-8 bytes for git branch (short name or short SHA when
   * detached). `null` + len=0 when cwd is outside a repo or the
   * shell-integration didn't ship the field.
   */
  const uint8_t *git_branch;
  uintptr_t git_branch_len;
  /**
   * 1 if `frozen_snapshot` is available (sealed block), 0 otherwise.
   */
  uint8_t has_frozen_snapshot;
  /**
   * CLI agent tag — `0` = none / unrecognised, otherwise one of the
   * `BT_CLI_AGENT_*` constants below. Stable across releases; new
   * agents append. Identifying a known agent lets the host paint a
   * brand icon next to the block header; does NOT change layout.
   */
  uint8_t cli_agent;
  uint8_t _pad3[2];
  /**
   * Live body height in grid rows. For sealed blocks this equals
   * `end_line - start_line`. For running blocks this is the block
   * grid's current `used_rows()` — the bottom-most non-blank visible
   * row + 1 (plus any history). The host should use this for the
   * block's body extent so a streaming TUI grows the block in real
   * time without pre-allocating the full PTY screen height.
   */
  uint32_t body_rows;
} BtBlockView;

typedef struct CellSnapshot {
  /**
   * Unicode scalar of the cell. 0 = blank. Wide-char trailing halves use char 0 with WIDE_TRAILING flag.
   */
  uint32_t ch;
  /**
   * Foreground colour, RGBA packed big-endian-style: 0xRRGGBBAA.
   */
  uint32_t fg_rgba;
  /**
   * Background colour, same encoding.
   */
  uint32_t bg_rgba;
  /**
   * Bitfield: 1=bold, 2=underline, 4=inverse, 8=italic, 16=wide_leading, 32=wide_trailing.
   */
  uint16_t flags;
} CellSnapshot;

typedef struct BtSnapshotView {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  /**
   * Equals `rows` when the cursor is scrolled off-screen.
   */
  uint16_t cursor_row;
  /**
   * 0 = at live bottom; positive = N rows into scrollback.
   */
  uint32_t display_offset;
  const struct CellSnapshot *cells;
  uintptr_t cell_count;
} BtSnapshotView;

/**
 * 8-bit-per-channel sRGB triple. The renderer-facing snapshot stores
 * premultiplied RGBA u32s; this type only exists at the host-config boundary.
 */
typedef struct BtRgb24 {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} BtRgb24;

/**
 * Flat C view of a `Palette`. 18 × `BtRgb24` = 54 bytes (no padding —
 * `#[repr(C)]` `BtRgb24` is 3 × u8). Swift passes a pointer; Rust copies in.
 */
typedef struct BtPaletteView {
  struct BtRgb24 default_fg;
  struct BtRgb24 default_bg;
  struct BtRgb24 ansi[16];
} BtPaletteView;

/**
 * A single snapshot row as seen from Swift / C.
 */
typedef struct CSnapshot {
  const char *id;
  const char *host_id;
  /**
   * -1 if no kill_reason was recorded.
   */
  int32_t kill_reason;
  /**
   * 0.0 if no killed_at was recorded.
   */
  double killed_at;
  /**
   * null if no last_cwd was recorded.
   */
  const char *last_cwd;
  /**
   * null if no last_command was recorded.
   */
  const char *last_command;
  /**
   * `i32::MIN` if no exit code was recorded.
   */
  int32_t last_exit_code;
  int64_t block_count;
} CSnapshot;

/**
 * Heap-allocated list returned by `bedterm_persistence_list`.
 * Free with `bedterm_persistence_free_list`.
 */
typedef struct CSnapshotList {
  const struct CSnapshot *items;
  uintptr_t count;
  struct OwnedListBacking *_owned;
} CSnapshotList;

/**
 * One entry per block: the BODY cell region + the surrounding Warp-style
 * panel chrome. Rust draws a rounded-rect panel for each visible block,
 * then paints cell quads inside. Header text remains a SwiftUI overlay
 * on top of the panel.
 */
typedef struct BtBlockLayoutEntry {
  /**
   * Matches `Block::id`. Looked up by linear scan over `term.blocks()`.
   */
  uint64_t block_id;
  /**
   * Top-left Y of the BODY (cells start here) in logical content
   * coordinates (pixels).
   */
  float body_y_top_px;
  /**
   * Body height in pixels (row_count × cell_height_px).
   */
  float body_height_px;
  /**
   * Top-left Y of the PANEL chrome (includes header). The rounded
   * panel BG paints from this Y down to `panel_y_top_px + panel_height_px`.
   */
  float panel_y_top_px;
  /**
   * Panel height in pixels (header + body + any inset).
   */
  float panel_height_px;
  /**
   * Panel left edge X in pixels.
   */
  float panel_x_left_px;
  /**
   * Panel width in pixels.
   */
  float panel_width_px;
  /**
   * Panel background RGBA (0xRRGGBBAA, big-endian packed). Pass 0 to
   * skip panel rendering for this entry (terminal pane fallback).
   */
  uint32_t panel_bg_rgba;
  /**
   * Panel corner radius in pixels.
   */
  float panel_corner_radius_px;
} BtBlockLayoutEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * `h` must be a valid `BtTerm *` returned by `bt_term_new`.
 */
uintptr_t bt_term_block_count(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid `BtTerm *`; `out` must point to a writable
 * `BtBlockView`. String pointers in `*out` are invalidated by the next
 * call as described in the module-level docs.
 */
int bt_term_block_at(struct BtTerm *h, uintptr_t idx, struct BtBlockView *out);

/**
 * Fetch the frozen body of a sealed block. Returns -1 if the block is
 * still running, missing, or the index is out of bounds. The cell
 * pointer in `*out` follows the same invalidation rules as
 * `bt_term_snapshot`.
 *
 * # Safety
 * `h` valid; `out` writable.
 */
int bt_term_block_snapshot(struct BtTerm *h, uintptr_t idx, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` valid.
 */
void bt_term_block_snapshot_release(struct BtTerm *h);

struct BtTerm *bt_term_new(uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_term_new` that has not yet been freed.
 */
void bt_term_free(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `bytes` must point to at least `len` bytes.
 */
void bt_term_feed(struct BtTerm *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_resize(struct BtTerm *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be a valid pointer to a `BtSnapshotView`.
 * The cell pointer in `*out` is valid until the next mutating call or `bt_term_snapshot_release`.
 */
int bt_term_snapshot(struct BtTerm *h, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_by(struct BtTerm *h, int32_t delta);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_to_bottom(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scroll_offset(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scrollback_lines(const struct BtTerm *h);

/**
 * Return the terminal's current mode flags, packed as `BT_MODE_*` bits
 * defined in `term.rs`. Swift mirrors the layout in `BedTermMode`.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_mode(const struct BtTerm *h);

/**
 * Cursor's current grid line on the active screen. Swift records this on
 * each block boundary so Block view can later snapshot a row range that
 * covers the block.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_current_line(const struct BtTerm *h);

/**
 * Grid-absolute line index of the screen's bottom row. Block view uses
 * this as the body's upper bound for running blocks so that TUI cells
 * drawn *below* the cursor via cursor-positioning escapes (claude / fzf
 * / gum) stay visible.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_screen_bottom_line(const struct BtTerm *h);

/**
 * Snapshot a row range from the active screen + scrollback. Same lifetime
 * contract as `bt_term_snapshot` — the cell pointer in `*out` is valid
 * until the next mutating call. `start_line` inclusive, `end_line`
 * exclusive; values outside the grid extent are clamped.
 *
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be writable.
 */
int bt_term_snapshot_range(struct BtTerm *h,
                           int32_t start_line,
                           int32_t end_line,
                           struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_snapshot_release(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `palette` must point to a valid,
 * aligned `BtPaletteView`, or be null (a null palette is a no-op).
 */
void bt_term_set_palette(struct BtTerm *h, const struct BtPaletteView *palette);

/**
 * Attach persistence to a `BtTerm` handle — a convenience shim over
 * `bedterm_persistence_attach` that accepts the opaque `BtTerm *` Swift
 * already owns rather than requiring Swift to materialise a bare `Terminal *`.
 *
 * # Safety
 * `h` must be a valid `BtTerm *` returned by `bt_term_new`.
 * `handle`, `snapshot_id`, and `host_id` follow the same safety contract
 * as `bedterm_persistence_attach`.
 */
void bt_term_attach_persistence(struct BtTerm *h,
                                struct PersistenceHandle *handle,
                                const char *snapshot_id,
                                const char *host_id);

/**
 * # Safety
 * `db_path` must be a valid NUL-terminated UTF-8 C string or null.
 * The returned pointer must be freed with `bedterm_persistence_close`.
 */
struct PersistenceHandle *bedterm_persistence_init(const char *db_path);

/**
 * # Safety
 * `handle` must be a pointer previously returned by
 * `bedterm_persistence_init` and not yet freed.
 */
void bedterm_persistence_close(struct PersistenceHandle *handle);

/**
 * Wire `terminal` to the persistence database held in `handle`, scoped to
 * `snapshot_id`. This function also ensures a `snapshots` row exists for
 * `snapshot_id` (idempotent — harmlessly fails with a constraint error if
 * the row was already inserted).
 *
 * After this call, every `CommandFinished` event processed by `terminal`
 * inserts a row into the `blocks` table. Blocks sealed by Ctrl-C
 * (Precmd-over-running-command path) are also persisted, with `exit_code`
 * set to NULL.
 *
 * # Safety
 *
 * - `handle`, `terminal`, `snapshot_id`, and `host_id` must all be valid
 *   non-null pointers.
 * - `snapshot_id` and `host_id` must be NUL-terminated UTF-8 C strings.
 * - The caller MUST keep `handle` alive until `terminal` is freed. The
 *   persistence sink installed by this function holds a raw pointer into
 *   `handle.db` — if the handle is freed while the terminal is still live,
 *   any subsequent block finalization will access freed memory.
 *
 * The intended call order is:
 *   1. `bedterm_persistence_attach(handle, term, sid, hid)` — on session open.
 *   2. Feed PTY bytes to `term` via `bedterm_feed` as usual.
 *   3. Free `term` (e.g. `bedterm_free`).
 *   4. `bedterm_persistence_close(handle)` — after the terminal is gone.
 */
void bedterm_persistence_attach(struct PersistenceHandle *handle,
                                struct Terminal *terminal,
                                const char *snapshot_id,
                                const char *host_id);

/**
 * Record that a session was killed.
 *
 * - `reason`: a `KillReason` discriminant (0–4).
 * - `last_cwd`, `last_command`: NUL-terminated UTF-8 or null.
 * - `last_exit_code` / `has_exit_code`: use `has_exit_code != 0` to pass a
 *   real exit code; `i32::MIN` is a legal exit code so a sentinel is not safe.
 *
 * # Safety
 * All non-null pointer arguments must point to valid NUL-terminated UTF-8.
 */
void bedterm_persistence_record_kill(struct PersistenceHandle *handle,
                                     const char *snapshot_id,
                                     int32_t reason,
                                     const char *last_cwd,
                                     const char *last_command,
                                     int32_t last_exit_code,
                                     int32_t has_exit_code);

/**
 * List all killed snapshots for a host, ordered newest-first.
 *
 * Returns a heap-allocated `CSnapshotList` that must be freed with
 * `bedterm_persistence_free_list`. Returns null on error.
 *
 * # Safety
 * `handle` and `host_id` must be valid non-null pointers.
 */
struct CSnapshotList *bedterm_persistence_list(struct PersistenceHandle *handle,
                                               const char *host_id);

/**
 * Free a list previously returned by `bedterm_persistence_list`.
 *
 * # Safety
 * `list` must have been returned by `bedterm_persistence_list` and not yet
 * freed.
 */
void bedterm_persistence_free_list(struct CSnapshotList *list);

/**
 * Delete a snapshot (and its blocks) from the database.
 *
 * # Safety
 * `handle` and `snapshot_id` must be valid non-null pointers; `snapshot_id`
 * must be a NUL-terminated UTF-8 C string.
 */
void bedterm_persistence_discard(struct PersistenceHandle *handle, const char *snapshot_id);

/**
 * Paint visible block bodies into `texture` for one frame. First
 * visible block clears the viewport; subsequent calls use Load. If no
 * block intersects the viewport, the viewport is still cleared.
 *
 * # Safety
 * `r`, `term`, `texture_ptr` must be valid live pointers. `entries`
 * must point to at least `entry_count` `BtBlockLayoutEntry` values
 * (or be null with `entry_count == 0`).
 */
int bt_renderer_draw_block_list(struct BtRenderer *r,
                                struct BtTerm *term,
                                const void *texture_ptr,
                                uint32_t viewport_w,
                                uint32_t viewport_h,
                                float scroll_y_px,
                                const struct BtBlockLayoutEntry *entries,
                                uintptr_t entry_count);

/**
 * # Safety
 * `mtl_device` and `mtl_queue` must be non-null `id<MTLDevice>` /
 * `id<MTLCommandQueue>` pointers. They are borrowed for the renderer's
 * lifetime; the caller (Swift) retains them.
 */
struct BtRenderer *bt_renderer_new(const void *mtl_device, const void *mtl_queue);

/**
 * # Safety
 * `r` must be a pointer returned by `bt_renderer_new` not yet freed.
 */
void bt_renderer_free(struct BtRenderer *r);

/**
 * # Safety
 * `r` must be a live `BtRenderer` pointer.
 */
void bt_renderer_set_font(struct BtRenderer *r, float pixel_size, float device_pixel_ratio);

/**
 * Write the renderer's current cell size (in PIXELS, scaled by the dpr
 * passed to `bt_renderer_set_font`) into `*out_w` and `*out_h`. Swift
 * divides by its display scale to obtain the point-space cell size used
 * for laying out CALayer overlays (cursor, selection) — keeping them
 * pixel-aligned with the glyphs the renderer paints.
 *
 * # Safety
 * `r` must be a live `BtRenderer`. `out_w` and `out_h` must be valid
 * pointers to `u32` slots the caller owns.
 */
void bt_renderer_cell_pixel_size(const struct BtRenderer *r, uint32_t *out_w, uint32_t *out_h);

/**
 * # Safety
 * `r` must be a live `BtRenderer` pointer, or null (null is a no-op).
 * Components are clamped to `[0, 1]` downstream by Metal; values outside
 * that range are tolerated.
 */
void bt_renderer_set_clear_color(struct BtRenderer *r,
                                 float red,
                                 float green,
                                 float blue,
                                 float alpha);

/**
 * # Safety
 * `r` must be a live `BtRenderer`. `term` must be a live `BtTerm` or null
 * (null is treated as "no terminal yet"). `drawable_texture` must be a
 * live `id<MTLTexture>`.
 */
int bt_renderer_draw(struct BtRenderer *r,
                     const struct BtTerm *term,
                     const void *drawable_texture,
                     uint32_t viewport_width_px,
                     uint32_t viewport_height_px,
                     double time_seconds);

/**
 * Render an arbitrary cell array — used by Block view to draw each
 * block's body (either a frozen snapshot of a sealed block or a fresh
 * row-range snapshot of a running block) through the same Metal pipeline
 * the main terminal view uses.
 *
 * `cells_len` must equal `cols as usize * rows as usize`. `cells` may be
 * null with `cells_len == 0` for an empty draw (clears the viewport).
 *
 * # Safety
 * `r` must be a live `BtRenderer`. `cells` (when non-null) must point to
 * `cells_len` valid `CellSnapshot` values for the duration of the call.
 * `drawable_texture` must be a live `id<MTLTexture>`.
 */
int bt_renderer_draw_cells(struct BtRenderer *r,
                           const struct CellSnapshot *cells,
                           uintptr_t cells_len,
                           uint16_t cols,
                           uint16_t rows,
                           const void *drawable_texture,
                           uint32_t viewport_width_px,
                           uint32_t viewport_height_px,
                           double time_seconds);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_CORE_H */
