// Auto-generated by cbindgen. Do not edit by hand.

#ifndef BEDTERM_CORE_H
#define BEDTERM_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Sentinel for a still-running block's `end_line`. Picked outside the legal
 * `i32` grid-line range alacritty produces. Public so the FFI layer can
 * surface it to Swift.
 */
#define BLOCK_END_LINE_RUNNING INT32_MIN

#define BT_BLOCK_END_LINE_RUNNING BLOCK_END_LINE_RUNNING

#define BT_CLI_AGENT_NONE 0

#define BT_CLI_AGENT_CLAUDE 1

#define BT_CLI_AGENT_GEMINI 2

#define BT_CLI_AGENT_CODEX 3

#define BT_CLI_AGENT_AMP 4

#define BT_CLI_AGENT_DROID 5

#define BT_CLI_AGENT_OPENCODE 6

#define BT_CLI_AGENT_COPILOT 7

#define BT_CLI_AGENT_PI 8

#define BT_CLI_AGENT_AUGGIE 9

#define BT_CLI_AGENT_CURSOR_CLI 10

#define BT_CLI_AGENT_GOOSE 11

#define BT_CLI_AGENT_HERMES 12

#define BT_CLI_AGENT_VIBE 13

/**
 * Two triangles per cell.
 */
#define VERTICES_PER_CELL 6

/**
 * Two triangles per panel.
 */
#define VERTICES_PER_PANEL 6

#define HORIZONTAL_PADDING_PT 12.0

#define BADGE_DIAMETER_PT 28.0

#define ICON_SIZE_PT 14.0

#define BADGE_TEXT_GAP_PT 8.0

#define ROW_GAP_PT 2.0

#define DIVIDER_THICKNESS_PT 1.0

#define FOREGROUND 0

#define BACKGROUND 1

#define BLACK 2

#define RED 3

#define GREEN 4

#define YELLOW 5

#define BLUE 6

#define MAGENTA 7

#define CYAN 8

#define WHITE 9

#define BRIGHT_BLACK 10

#define BRIGHT_RED 11

#define BRIGHT_GREEN 12

#define BRIGHT_YELLOW 13

#define BRIGHT_BLUE 14

#define BRIGHT_MAGENTA 15

#define BRIGHT_CYAN 16

#define BRIGHT_WHITE 17

#define BT_MODE_ALT_SCREEN (1 << 0)

#define BT_MODE_BRACKETED_PASTE (1 << 1)

#define BT_MODE_MOUSE_REPORT (1 << 2)

#define BT_MODE_APP_CURSOR (1 << 3)

#define BT_MODE_APP_KEYPAD (1 << 4)

#define BT_MODE_FOCUS_IN_OUT (1 << 5)

#define VINTR 3

#define VEOF 4

#define VERASE 127

typedef struct BtMockTty BtMockTty;

typedef struct BtRenderer BtRenderer;

typedef struct BtTerm BtTerm;

typedef struct Flags Flags;

typedef struct BtBlockView {
  uint64_t id;
  int32_t start_line;
  /**
   * `BT_BLOCK_END_LINE_RUNNING` while the block is running.
   */
  int32_t end_line;
  /**
   * 1 if running, 0 otherwise.
   */
  uint8_t is_running;
  uint8_t has_exit_code;
  uint8_t _pad[2];
  int32_t exit_code;
  /**
   * 0 when the shell didn't ship `dur=`.
   */
  uint64_t duration_ms;
  uint8_t has_duration;
  uint8_t _pad2[7];
  /**
   * UTF-8 bytes for command. `null` + len=0 when empty.
   */
  const uint8_t *command;
  uintptr_t command_len;
  /**
   * UTF-8 bytes for working directory. `null` + len=0 when missing.
   */
  const uint8_t *cwd;
  uintptr_t cwd_len;
  /**
   * UTF-8 bytes for git branch (short name or short SHA when
   * detached). `null` + len=0 when cwd is outside a repo or the
   * shell-integration didn't ship the field.
   */
  const uint8_t *git_branch;
  uintptr_t git_branch_len;
  /**
   * 1 if `frozen_snapshot` is available (sealed block), 0 otherwise.
   */
  uint8_t has_frozen_snapshot;
  /**
   * CLI agent tag — `0` = none / unrecognised, otherwise one of the
   * `BT_CLI_AGENT_*` constants below. Stable across releases; new
   * agents append. Identifying a known agent lets the host paint a
   * brand icon next to the block header; does NOT change layout.
   */
  uint8_t cli_agent;
  uint8_t _pad3[2];
  /**
   * Live body height in grid rows. For sealed blocks this equals
   * `end_line - start_line`. For running blocks this is the block
   * grid's current `used_rows()` — the bottom-most non-blank visible
   * row + 1 (plus any history). The host should use this for the
   * block's body extent so a streaming TUI grows the block in real
   * time without pre-allocating the full PTY screen height.
   */
  uint32_t body_rows;
} BtBlockView;

typedef struct CellSnapshot {
  /**
   * Unicode scalar of the cell. 0 = blank. Wide-char trailing halves use char 0 with WIDE_TRAILING flag.
   */
  uint32_t ch;
  /**
   * Foreground colour, RGBA packed big-endian-style: 0xRRGGBBAA.
   */
  uint32_t fg_rgba;
  /**
   * Background colour, same encoding.
   */
  uint32_t bg_rgba;
  /**
   * Bitfield: 1=bold, 2=underline, 4=inverse, 8=italic, 16=wide_leading, 32=wide_trailing.
   */
  uint16_t flags;
} CellSnapshot;

typedef struct BtSnapshotView {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  /**
   * Equals `rows` when the cursor is scrolled off-screen.
   */
  uint16_t cursor_row;
  /**
   * 0 = at live bottom; positive = N rows into scrollback.
   */
  uint32_t display_offset;
  const struct CellSnapshot *cells;
  uintptr_t cell_count;
} BtSnapshotView;

/**
 * 8-bit-per-channel sRGB triple. The renderer-facing snapshot stores
 * premultiplied RGBA u32s; this type only exists at the host-config boundary.
 */
typedef struct BtRgb24 {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} BtRgb24;

/**
 * Flat C view of a `Palette`. 18 × `BtRgb24` = 54 bytes (no padding —
 * `#[repr(C)]` `BtRgb24` is 3 × u8). Swift passes a pointer; Rust copies in.
 */
typedef struct BtPaletteView {
  struct BtRgb24 default_fg;
  struct BtRgb24 default_bg;
  struct BtRgb24 ansi[16];
} BtPaletteView;

/**
 * One entry per block: the BODY cell region plus the panel chrome
 * rect. Headers are emitted separately via `BtBlockHeaderEntry`.
 */
typedef struct BtBlockLayoutEntry {
  /**
   * Matches `Block::id`. Looked up by linear scan over `term.blocks()`.
   */
  uint64_t block_id;
  /**
   * Top-left Y of the BODY (cells start here) in logical content
   * coordinates (pixels).
   */
  float body_y_top_px;
  /**
   * Body height in pixels (row_count × cell_height_px).
   */
  float body_height_px;
  /**
   * Top-left Y of the PANEL chrome (includes header). The rounded
   * panel BG paints from this Y down to `panel_y_top_px + panel_height_px`.
   */
  float panel_y_top_px;
  /**
   * Panel height in pixels (header + body + any inset).
   */
  float panel_height_px;
  /**
   * Panel left edge X in pixels.
   */
  float panel_x_left_px;
  /**
   * Panel width in pixels.
   */
  float panel_width_px;
  /**
   * Panel background RGBA (0xRRGGBBAA, big-endian packed). Pass 0 to
   * skip panel rendering for this entry (terminal pane fallback).
   */
  uint32_t panel_bg_rgba;
  /**
   * Panel corner radius in pixels.
   */
  float panel_corner_radius_px;
} BtBlockLayoutEntry;

/**
 * One entry per visible block header band. Sticky descriptors use the
 * same struct with `is_sticky = 1` and `header_y_top_px` in
 * **screen-space** (post-scroll) rather than content-space.
 */
typedef struct BtBlockHeaderEntry {
  uint64_t block_id;
  /**
   * For natural headers: top Y in **content** coords (pre-scroll).
   * For sticky (is_sticky=1): top Y in **screen** coords.
   */
  float header_y_top_px;
  float header_height_px;
  float panel_x_left_px;
  float panel_width_px;
  /**
   * UTF-8 bytes of the command string. Nullable when `command_len == 0`.
   */
  const uint8_t *command_utf8;
  uint32_t command_len;
  /**
   * UTF-8 bytes of the subtitle string (e.g. "exit 0 · 1.2s").
   * Nullable when `subtitle_len == 0`.
   */
  const uint8_t *subtitle_utf8;
  uint32_t subtitle_len;
  /**
   * 0 = no badge; nonzero values mirror the Swift `CLIAgent` enum.
   * Branded slots known to the icon atlas (Claude=1, Codex=2);
   * everything else falls back to the generic glyph.
   */
  uint8_t agent_id;
  uint8_t _pad[3];
  /**
   * Badge circle fill (0xRRGGBBAA).
   */
  uint32_t badge_tint_rgba;
  /**
   * Command text colour.
   */
  uint32_t command_fg_rgba;
  /**
   * Subtitle text colour.
   */
  uint32_t subtitle_fg_rgba;
  /**
   * Hairline divider rgba. For natural headers, painted ABOVE the
   * band; for sticky headers, painted BELOW (so the pinned chrome
   * reads as a section header floating above the scrolling body).
   * Pass 0 to skip.
   */
  uint32_t divider_rgba;
  /**
   * 1 = this is the pinned sticky band. Drawn last (z-sorted on top)
   * and given an opaque surface-coloured fill so scrolling body
   * cells underneath don't bleed through.
   */
  uint8_t is_sticky;
  uint8_t _pad2[3];
} BtBlockHeaderEntry;





#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * `h` must be a valid `BtTerm *` returned by `bt_term_new`.
 */
uintptr_t bt_term_block_count(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid `BtTerm *`; `out` must point to a writable
 * `BtBlockView`. String pointers in `*out` are invalidated by the next
 * call as described in the module-level docs.
 */
int bt_term_block_at(struct BtTerm *h, uintptr_t idx, struct BtBlockView *out);

/**
 * Fetch the frozen body of a sealed block. Returns -1 if the block is
 * still running, missing, or the index is out of bounds. The cell
 * pointer in `*out` follows the same invalidation rules as
 * `bt_term_snapshot`.
 *
 * # Safety
 * `h` valid; `out` writable.
 */
int bt_term_block_snapshot(struct BtTerm *h, uintptr_t idx, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` valid.
 */
void bt_term_block_snapshot_release(struct BtTerm *h);

struct BtTerm *bt_term_new(uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_term_new` that has not yet been freed.
 */
void bt_term_free(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `bytes` must point to at least `len` bytes.
 */
void bt_term_feed(struct BtTerm *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_resize(struct BtTerm *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be a valid pointer to a `BtSnapshotView`.
 * The cell pointer in `*out` is valid until the next mutating call or `bt_term_snapshot_release`.
 */
int bt_term_snapshot(struct BtTerm *h, struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_by(struct BtTerm *h, int32_t delta);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_scroll_to_bottom(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scroll_offset(const struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_scrollback_lines(const struct BtTerm *h);

/**
 * Return the terminal's current mode flags, packed as `BT_MODE_*` bits
 * defined in `term.rs`. Swift mirrors the layout in `BedTermMode`.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
uint32_t bt_term_mode(const struct BtTerm *h);

/**
 * Cursor's current grid line on the active screen. Swift records this on
 * each block boundary so Block view can later snapshot a row range that
 * covers the block.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_current_line(const struct BtTerm *h);

/**
 * Grid-absolute line index of the screen's bottom row. Block view uses
 * this as the body's upper bound for running blocks so that TUI cells
 * drawn *below* the cursor via cursor-positioning escapes (claude / fzf
 * / gum) stay visible.
 *
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
int32_t bt_term_screen_bottom_line(const struct BtTerm *h);

/**
 * Snapshot a row range from the active screen + scrollback. Same lifetime
 * contract as `bt_term_snapshot` — the cell pointer in `*out` is valid
 * until the next mutating call. `start_line` inclusive, `end_line`
 * exclusive; values outside the grid extent are clamped.
 *
 * # Safety
 * `h` must be a valid, non-freed handle. `out` must be writable.
 */
int bt_term_snapshot_range(struct BtTerm *h,
                           int32_t start_line,
                           int32_t end_line,
                           struct BtSnapshotView *out);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_term_snapshot_release(struct BtTerm *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle. `palette` must point to a valid,
 * aligned `BtPaletteView`, or be null (a null palette is a no-op).
 */
void bt_term_set_palette(struct BtTerm *h, const struct BtPaletteView *palette);

/**
 * Paint visible block bodies + header bands into `texture` for one
 * frame. First visible block clears the viewport; subsequent calls use
 * Load. If no block intersects the viewport, the viewport is still
 * cleared.
 *
 * # Safety
 * `r`, `term`, `texture_ptr` must be valid live pointers. `entries`
 * must point to at least `entry_count` `BtBlockLayoutEntry` values
 * (or be null with `entry_count == 0`). Same for `headers` /
 * `header_count`. UTF-8 pointers inside header entries must outlive
 * the call.
 */
int bt_renderer_draw_block_list(struct BtRenderer *r,
                                struct BtTerm *term,
                                const void *texture_ptr,
                                uint32_t viewport_w,
                                uint32_t viewport_h,
                                float scroll_y_px,
                                const struct BtBlockLayoutEntry *entries,
                                uintptr_t entry_count,
                                const struct BtBlockHeaderEntry *headers,
                                uintptr_t header_count);

/**
 * Push current UI font sizes into the renderer. Called by Swift on
 * init and whenever the trait collection changes (Dynamic Type, scale).
 * `*_px` are in **pixels** (point size × screen scale).
 *
 * # Safety
 * `r` must be a valid live pointer.
 */
int bt_renderer_set_ui_font_sizes_px(struct BtRenderer *r,
                                     float subheadline_px,
                                     float caption2_px,
                                     float scale);

/**
 * # Safety
 * `mtl_device` and `mtl_queue` must be non-null `id<MTLDevice>` /
 * `id<MTLCommandQueue>` pointers. They are borrowed for the renderer's
 * lifetime; the caller (Swift) retains them.
 */
struct BtRenderer *bt_renderer_new(const void *mtl_device, const void *mtl_queue);

/**
 * # Safety
 * `r` must be a pointer returned by `bt_renderer_new` not yet freed.
 */
void bt_renderer_free(struct BtRenderer *r);

/**
 * # Safety
 * `r` must be a live `BtRenderer` pointer.
 */
void bt_renderer_set_font(struct BtRenderer *r, float pixel_size, float device_pixel_ratio);

/**
 * Write the renderer's current cell size (in PIXELS, scaled by the dpr
 * passed to `bt_renderer_set_font`) into `*out_w` and `*out_h`. Swift
 * divides by its display scale to obtain the point-space cell size used
 * for laying out CALayer overlays (cursor, selection) — keeping them
 * pixel-aligned with the glyphs the renderer paints.
 *
 * # Safety
 * `r` must be a live `BtRenderer`. `out_w` and `out_h` must be valid
 * pointers to `u32` slots the caller owns.
 */
void bt_renderer_cell_pixel_size(const struct BtRenderer *r, uint32_t *out_w, uint32_t *out_h);

/**
 * # Safety
 * `r` must be a live `BtRenderer` pointer, or null (null is a no-op).
 * Components are clamped to `[0, 1]` downstream by Metal; values outside
 * that range are tolerated.
 */
void bt_renderer_set_clear_color(struct BtRenderer *r,
                                 float red,
                                 float green,
                                 float blue,
                                 float alpha);

/**
 * # Safety
 * `r` must be a live `BtRenderer`. `term` must be a live `BtTerm` or null
 * (null is treated as "no terminal yet"). `drawable_texture` must be a
 * live `id<MTLTexture>`.
 */
int bt_renderer_draw(struct BtRenderer *r,
                     const struct BtTerm *term,
                     const void *drawable_texture,
                     uint32_t viewport_width_px,
                     uint32_t viewport_height_px,
                     double time_seconds);

/**
 * Render an arbitrary cell array — used by Block view to draw each
 * block's body (either a frozen snapshot of a sealed block or a fresh
 * row-range snapshot of a running block) through the same Metal pipeline
 * the main terminal view uses.
 *
 * `cells_len` must equal `cols as usize * rows as usize`. `cells` may be
 * null with `cells_len == 0` for an empty draw (clears the viewport).
 *
 * # Safety
 * `r` must be a live `BtRenderer`. `cells` (when non-null) must point to
 * `cells_len` valid `CellSnapshot` values for the duration of the call.
 * `drawable_texture` must be a live `id<MTLTexture>`.
 */
int bt_renderer_draw_cells(struct BtRenderer *r,
                           const struct CellSnapshot *cells,
                           uintptr_t cells_len,
                           uint16_t cols,
                           uint16_t rows,
                           const void *drawable_texture,
                           uint32_t viewport_width_px,
                           uint32_t viewport_height_px,
                           double time_seconds);

/**
 * # Safety
 * `opts_json` must be either null or point to a NUL-terminated UTF-8 string
 * owned by the caller for the duration of this call.
 */
struct BtMockTty *bt_mock_tty_create(uint32_t program, const char *opts_json);

/**
 * # Safety
 * `h` must be a pointer returned by `bt_mock_tty_create` that has not been freed.
 */
void bt_mock_tty_free(struct BtMockTty *h);

/**
 * # Safety
 * `h` must be a valid, non-freed handle.
 */
void bt_mock_tty_set_output_callback(struct BtMockTty *h, void (*cb)(const uint8_t*,
                                                                     uintptr_t,
                                                                     void*), void *user_data);

/**
 * # Safety
 * `h` must be valid; `bytes` must point to at least `len` bytes (or be null when len == 0).
 */
int32_t bt_mock_tty_write(struct BtMockTty *h, const uint8_t *bytes, uintptr_t len);

/**
 * # Safety
 * `h` must be valid.
 */
void bt_mock_tty_resize(struct BtMockTty *h, uint16_t cols, uint16_t rows);

/**
 * # Safety
 * `h` must be valid.
 */
void bt_mock_tty_tick(struct BtMockTty *h, uint64_t now_ms);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BEDTERM_CORE_H */
